/**
 * @Autor  Marco Alberto Chávez Fernández
 * @Correo: mchavez297@accitesz.com
 *
 * @Autor José Carlos Esparza de Anda
 * @Correo: jesparza301@accitesz.com
 *
 * @Autor José Ángel Madrigal Plancarte
 * @Correo: jmadrigal323@accitesz.com
 *
 * @Docente: Dr. Francisco Rodríguez Díaz
 * @Asignatura: Ing. de Software
 * @Escuela: Instituto Tecnologico de Estudios Superiores de Zamora
 * @Semestre : 7
 * @Grupo: B
 * @Carrera: Ing. en Sistemas Computacionales
 *
 * **Descripcion
 * @since VER1.0
 */
package GUI;

/*
* Importacion de las clase requeridas
 */
import Conexion.ConexionBD;
import Modelos.CorteCaja;
import Modelos.CorteVenta;
import Modelos.Venta;

public class CortesMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form CortesMainFrame
     */
    /*
    *@param conexion es una propiedad de la clase ConexionBD que define la conexion de la base de datos
    *@param CorteActutal es una propiedad de la clase CorteCaja para realizar operaciones con el corte actual de la venta
     */
    ConexionBD conexion;
    CorteCaja CorteActual;

    /*
    * Constructor de la clase cuando el usuario tiene un corte activo
    *@param conexion define la conexion con la que se creara la clase
    *@param corte define el corte actual de la interface
     */
    public CortesMainFrame(ConexionBD conexion, CorteCaja corte) {
        initComponents();
        this.conexion = conexion;
        this.CorteActual = corte;
        recuperaCorte();
        llenaEtiquetas();
    }

    /*
    * Constructor de la clase cuando el usuario no tiene ningun corte activo
    * @param conexion Recibe la conexion de la BD
    * @param ventaActual recibe la venta que se ha generado para continuar con las relaciones con los Cortes
    * @param fondoInicial indica la cantidad de dinero con la que se abrira el corteActual
     */
    public CortesMainFrame(ConexionBD conexion, Venta ventaActual, Float fondoInicial) {
        initComponents();
        this.conexion = conexion;
        inicializarCorte(fondoInicial);
        CorteVenta nuevaVentaCorte = new CorteVenta(ventaActual.getIdVenta(), this.CorteActual.getIdCorte());
        conexion.insertarCorteVenta(nuevaVentaCorte);
        llenaEtiquetas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
     El Codigo initComponents es generado por Netbeans
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Imprimir = new javax.swing.JButton();
        btn_CreaTicket = new javax.swing.JButton();
        btn_Retirar = new javax.swing.JButton();
        lbl_CorteId = new javax.swing.JLabel();
        lbl_CorteId1 = new javax.swing.JLabel();
        lbl_TotalVenta = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JButton();
        btn_CerrarCorte = new javax.swing.JButton();
        lbl_Nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCommodity+ by White Company® ");
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cortes/Reimprimir_Retiro.png"))); // NOI18N
        btn_Imprimir.setContentAreaFilled(false);
        btn_Imprimir.setDefaultCapable(false);
        btn_Imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ImprimirMouseExited(evt);
            }
        });
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        btn_CreaTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cortes/Generar_Ticket.png"))); // NOI18N
        btn_CreaTicket.setBorderPainted(false);
        btn_CreaTicket.setContentAreaFilled(false);
        btn_CreaTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CreaTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CreaTicketMouseExited(evt);
            }
        });
        btn_CreaTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreaTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CreaTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btn_Retirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cortes/Realizar_Retiro.png"))); // NOI18N
        btn_Retirar.setBorderPainted(false);
        btn_Retirar.setContentAreaFilled(false);
        btn_Retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RetirarMouseExited(evt);
            }
        });
        btn_Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        lbl_CorteId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_CorteId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_CorteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 90, 30));

        lbl_CorteId1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_CorteId1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CorteId1.setText("Corte ID");
        jPanel1.add(lbl_CorteId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        lbl_TotalVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TotalVenta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TotalVenta.setText("0.0");
        jPanel1.add(lbl_TotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, 20));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Volver.png"))); // NOI18N
        btn_Atras.setBorderPainted(false);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_CerrarCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cortes/Cerrar_Corte.png"))); // NOI18N
        btn_CerrarCorte.setBorderPainted(false);
        btn_CerrarCorte.setContentAreaFilled(false);
        btn_CerrarCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CerrarCorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CerrarCorteMouseExited(evt);
            }
        });
        btn_CerrarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarCorteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CerrarCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre.setText("Cortes");
        jPanel1.add(lbl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 80, 40));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total $");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 770, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    /*
    * Metodo para rellenar las etiquetas de la inteface
    * No Recibe ningun parametro
     */
    private void llenaEtiquetas() {
        lbl_CorteId.setText(String.valueOf(this.CorteActual.getIdCorte()));
        this.CorteActual.setTotalVenta(conexion.consultarCorteVentaTotal(CorteActual.getIdCorte()));
        if (CorteActual.getTotalVenta() == null) {
            lbl_TotalVenta.setText("0.00");
        } else {
            lbl_TotalVenta.setText(String.valueOf(this.CorteActual.getTotalVenta()));
        }

    }

    /*
    * Este evento cierra el CorteActual del usuario y esta relacionado con el btn_CerrarCorte
     */
    private void btn_CerrarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CerrarCorteActionPerformed

    /*
    * Este evento regresa a la pagina principal de ventas y esta relacionado con el btn_Atras
     */
    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        VentasMainFrame ventas = new VentasMainFrame(this.conexion);
        ventas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_AtrasActionPerformed

    /*
    * Este evento genera un nuevo ticket y esta relacionado con el btn_CreaTicket
     */
    private void btn_CreaTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreaTicketActionPerformed
        TicketMainFrame addTicket = new TicketMainFrame(this.conexion, this.CorteActual);
        addTicket.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CreaTicketActionPerformed

    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_CreaTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CreaTicketMouseEntered
        lbl_Nombre.setText("Generar");
        jLabel2.setText("Ticket");
    }//GEN-LAST:event_btn_CreaTicketMouseEntered

    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_CreaTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CreaTicketMouseExited
        lbl_Nombre.setText("Cortes");
        jLabel2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btn_CreaTicketMouseExited

    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_RetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RetirarMouseEntered
        lbl_Nombre.setText("Realizar");
        jLabel2.setText("Retiro");    // TODO add your handling code here:
    }//GEN-LAST:event_btn_RetirarMouseEntered

    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_RetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RetirarMouseExited
        lbl_Nombre.setText("Cortes");
        jLabel2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btn_RetirarMouseExited

    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_ImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ImprimirMouseEntered
        lbl_Nombre.setText("Reimprimir");
        jLabel2.setText("Ticket"); // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirMouseEntered
    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_ImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ImprimirMouseExited
        lbl_Nombre.setText("Cortes");
        jLabel2.setText("");/// TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirMouseExited
    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_CerrarCorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarCorteMouseEntered
        lbl_Nombre.setText("Cerrar");
        jLabel2.setText("Corte"); /// TODO add your handling code here:
    }//GEN-LAST:event_btn_CerrarCorteMouseEntered
    /*
    * Este evento es para mejoras visuales de la interface
    * Escribe en el lbl_Nombre la opcion seleccionada
     */
    private void btn_CerrarCorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CerrarCorteMouseExited
        lbl_Nombre.setText("Cortes");
        jLabel2.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_btn_CerrarCorteMouseExited

    /*
    * Este evento permite generar retiros de caja  y esta relacionado con el btn_Retirar
     */
    private void btn_RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RetirarActionPerformed
        RealizarRetiroFrame retiros = new RealizarRetiroFrame(this.conexion,this.CorteActual);
        this.setVisible(false);
        retiros.setVisible(true);
    }//GEN-LAST:event_btn_RetirarActionPerformed
    
    /*
    * La funcion inicializarCorte permite crear un nuevo corte e insertarlo 
    *cuando el usuario no tienen ningun corte activo
    *@param fondoInicial es la cantidad con la que se crea el corte y se 
    *guarda en fondoInicial de la base de daatos
    */
    private void inicializarCorte(Float fondoInicial) {
        java.util.Date utilDate = new java.util.Date();
        java.sql.Time hora = new java.sql.Time(utilDate.getTime());
        java.sql.Date fecha = new java.sql.Date(utilDate.getTime());
        CorteCaja nuevoCorte = new CorteCaja();
        nuevoCorte.setIdUsuario(this.conexion.getUser().getIdUsuario());
        nuevoCorte.setFondoInicial(fondoInicial);
        nuevoCorte.setTotalVenta(0.0f);
        nuevoCorte.setTotalRetiros(0.0f);
        nuevoCorte.setTotalCorte(0.0f);
        nuevoCorte.setHoraInicial(hora);
        nuevoCorte.setEstatus("A");
        nuevoCorte.setFecha(fecha);
        if (conexion.insertarCorteCaja(nuevoCorte)) {
            this.CorteActual = nuevoCorte;
        }
        recuperaCorte();
    }
    
    /*
    * La funcion recupera corte permite recuperar el corte del usuario
    * si este tiene activo uno
    * No requiere parametros
    */
    
    private void recuperaCorte() {
        java.util.Date utilDate = new java.util.Date();
        java.sql.Date fecha = new java.sql.Date(utilDate.getTime());
        this.CorteActual = conexion.consultaCorteCaja(fecha, conexion.getUser().getIdUsuario());
       

    }

    /*
    * La funcion recupera corte permite cerrar el corte del usuario
    * No requiere parametros
    */
    private void cierraCorte() {
        this.CorteActual.setEstatus("C");
        /*
        Calcular total venta
        Calcular Total Retiros
        Descontar el totla de los retiros
         */

    }

    /**
     * @param args the command line arguments
     */
    
    /*
    * Variables creadas por NetBeans para el uso de los componentes de la 
    * interface
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_CerrarCorte;
    private javax.swing.JButton btn_CreaTicket;
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btn_Retirar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_CorteId;
    private javax.swing.JLabel lbl_CorteId1;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_TotalVenta;
    // End of variables declaration//GEN-END:variables
}
