/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Carlos EsparzadeAnda
 */
public class PantallaCarga extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCarga
     */
    public PantallaCarga() {
        initComponents();
        int carga =1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSProgressCircleBeanInfo1 = new rojerusan.componentes.RSProgressCircleBeanInfo();
        rSProgressCircleUIAnimated11 = new rojerusan.complementos.RSProgressCircleUIAnimated1();
        rSProgressCircleBeanInfo2 = new rojerusan.componentes.RSProgressCircleBeanInfo();
        rSProgressCircleBeanInfo3 = new rojerusan.componentes.RSProgressCircleBeanInfo();
        rSProgressCircleAnimatedUnoBeanInfo1 = new rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo();
        rSProgressCircleAnimatedUnoBeanInfo2 = new rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo();
        rSProgressBarSinTextBeanInfo1 = new rojerusan.componentes.RSProgressBarSinTextBeanInfo();
        rSProgressBarBeanInfo1 = new rojerusan.componentes.RSProgressBarBeanInfo();
        rSProgressBarAnimatedBeanInfo1 = new rojerusan.componentes.RSProgressBarAnimatedBeanInfo();
        rSProgressBarAnimatedBeanInfo2 = new rojerusan.componentes.RSProgressBarAnimatedBeanInfo();
        rSProgressMaterialBeanInfo1 = new rojerusan.componentes.RSProgressMaterialBeanInfo();
        rSProgressBarBeanInfo2 = new rojerusan.componentes.RSProgressBarBeanInfo();
        rSProgressBarAnimatedBeanInfo3 = new rojerusan.componentes.RSProgressBarAnimatedBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rSProgressBar1 = new rojerusan.componentes.RSProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSProgressBar1.setForeground(new java.awt.Color(255, 0, 204));
        rSProgressBar1.setToolTipText("");
        rSProgressBar1.setValue(0);
        rSProgressBar1.setColorBorde(new java.awt.Color(255, 255, 255));
        rSProgressBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        rSProgressBar1.setDoubleBuffered(true);
        rSProgressBar1.setRequestFocusEnabled(false);
        jPanel3.add(rSProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 520, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGO_SoftCommodity+_V1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 690, 310));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private rojerusan.componentes.RSProgressBar rSProgressBar1;
    private rojerusan.componentes.RSProgressBarAnimatedBeanInfo rSProgressBarAnimatedBeanInfo1;
    private rojerusan.componentes.RSProgressBarAnimatedBeanInfo rSProgressBarAnimatedBeanInfo2;
    private rojerusan.componentes.RSProgressBarAnimatedBeanInfo rSProgressBarAnimatedBeanInfo3;
    private rojerusan.componentes.RSProgressBarBeanInfo rSProgressBarBeanInfo1;
    private rojerusan.componentes.RSProgressBarBeanInfo rSProgressBarBeanInfo2;
    private rojerusan.componentes.RSProgressBarSinTextBeanInfo rSProgressBarSinTextBeanInfo1;
    private rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo rSProgressCircleAnimatedUnoBeanInfo1;
    private rojerusan.componentes.RSProgressCircleAnimatedUnoBeanInfo rSProgressCircleAnimatedUnoBeanInfo2;
    private rojerusan.componentes.RSProgressCircleBeanInfo rSProgressCircleBeanInfo1;
    private rojerusan.componentes.RSProgressCircleBeanInfo rSProgressCircleBeanInfo2;
    private rojerusan.componentes.RSProgressCircleBeanInfo rSProgressCircleBeanInfo3;
    private rojerusan.complementos.RSProgressCircleUIAnimated1 rSProgressCircleUIAnimated11;
    private rojerusan.componentes.RSProgressMaterialBeanInfo rSProgressMaterialBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
