/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Conexion.ConexionBD;
import Modelos.CorteCaja;
import Modelos.Venta;

/**
 *
 * @author Marco Chavez
 */
public class VentasMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form VentasMainFrame
     */
    ConexionBD conexion;
    Venta ventaActual;
    java.sql.Date Fecha;

    public VentasMainFrame(ConexionBD conexion) {
        initComponents();
        this.conexion = conexion;
        java.util.Date d = new java.util.Date();
        Fecha = new java.sql.Date(d.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_CrearCorte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_TotalVenta = new javax.swing.JLabel();
        btn_ContinuarCorte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftCommodity+ by White Company® ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CrearCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ventas/Crear_Corte.png"))); // NOI18N
        btn_CrearCorte.setBorderPainted(false);
        btn_CrearCorte.setContentAreaFilled(false);
        btn_CrearCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CrearCorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CrearCorteMouseExited(evt);
            }
        });
        btn_CrearCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearCorteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CrearCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 260, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total de Venta del dia $");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        lbl_TotalVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TotalVenta.setForeground(new java.awt.Color(237, 174, 195));
        lbl_TotalVenta.setText("0.00");
        jPanel1.add(lbl_TotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        btn_ContinuarCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ventas/Continuar_Corte.png"))); // NOI18N
        btn_ContinuarCorte.setBorderPainted(false);
        btn_ContinuarCorte.setContentAreaFilled(false);
        btn_ContinuarCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ContinuarCorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ContinuarCorteMouseExited(evt);
            }
        });
        btn_ContinuarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ContinuarCorteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ContinuarCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 260, 260));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        texto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 160, -1, -1));

        texto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Volver.png"))); // NOI18N
        btn_Atras.setBorderPainted(false);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearCorteActionPerformed
        IniciaCorteFrame corte = new IniciaCorteFrame(this.conexion, ventaActual);
        corte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CrearCorteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (conexion.consultarVentaDiaria(Fecha)) {
            ventaActual = conexion.consultarVenta(Fecha);
            ventaActual.setTotalVenta(conexion.consultarVentaTotalVenta(Fecha));
            lbl_TotalVenta.setText(String.valueOf(ventaActual.getTotalVenta()));
            //
        } else {
            Venta ventaDiaria = new Venta();
            ventaDiaria.setFecha(Fecha);
            ventaDiaria.setTotalVenta(0);
            conexion.insertarVenta(ventaDiaria);
             ventaActual = conexion.consultarVenta(Fecha);
        }
        CorteCaja corte;
        corte = conexion.consultaCorteCaja(Fecha, conexion.getUser().getIdUsuario());
        if (corte.getIdUsuario() == null) {
            btn_CrearCorte.setEnabled(true);
            btn_ContinuarCorte.setEnabled(false);
        } else {

            btn_CrearCorte.setEnabled(false);
            btn_ContinuarCorte.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_ContinuarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContinuarCorteActionPerformed
        CorteCaja corte;
        corte = conexion.consultaCorteCaja(Fecha, conexion.getUser().getIdUsuario());
        CortesMainFrame cortes = new CortesMainFrame(this.conexion, corte);
        cortes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ContinuarCorteActionPerformed

    private void btn_CrearCorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearCorteMouseEntered
        texto1.setText("Crear");
        texto2.setText("Corte");
    }//GEN-LAST:event_btn_CrearCorteMouseEntered

    private void btn_CrearCorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearCorteMouseExited
        texto1.setText("");
        texto2.setText(""); // TODO add your handling code here:

    }//GEN-LAST:event_btn_CrearCorteMouseExited

    private void btn_ContinuarCorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ContinuarCorteMouseEntered
        texto1.setText("Continuar");
        texto2.setText("Corte");
    }//GEN-LAST:event_btn_ContinuarCorteMouseEntered

    private void btn_ContinuarCorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ContinuarCorteMouseExited
        texto1.setText("");
        texto2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btn_ContinuarCorteMouseExited

    /*
    * Este evento regresa al menu principal y esta relacionado con el btn_Atras
     */
    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        MenuPrincipalFrame menu = new MenuPrincipalFrame(this.conexion);
        this.setVisible(false);
        menu.setVisible(true);

    }//GEN-LAST:event_btn_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_ContinuarCorte;
    private javax.swing.JButton btn_CrearCorte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_TotalVenta;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
